### PR TITLE
Fix `ours` resolution typo

### PR DESCRIPTION
**Pull request by puffnfresh**
Should be different from `theirs`

### CODE REVIEW

**Comment by puffnfresh** [comment]
Just guessing :camel:

**Comment by puffnfresh** [comment]
Actually, pretty sure I flipped the wrong one :cactus:

**Comment by liamoc** [comment]
Wait, really?

**Comment by liamoc** [comment]
Oh, right, I'll change it.

**Comment by liamoc** [comment]
Alright, I fixed it.

**Pull request merged**
